In [1]:
#Lets import all the required libraries 
import selenium # Libraries that is used to work  with selenium
from selenium import webdriver # importing web driver module from selenium to open automated edge window
import pandas as pd # to create dataframe
from selenium.webdriver.common.by import By#importing inbuild class BY
import warnings #to ignore any sort warnings
warnings.filterwarnings('ignore')
import time# used to stop search engine for few seconds

In [2]:
import re
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
from selenium.webdriver.support.ui import WebDriverWait

In [133]:
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [4]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=JAI&destinationCountry=IN&flexi=0&flight_depart_date=06%2F01%2F2023&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=45747080776&version=1.1&viewName=normal'

In [9]:
driver.get(url)

In [6]:
for _ in range(200):

    driver.execute_script("window.scrollBy(0,1000)")

In [218]:
# Scraping details of product for which you want
Flight_Name=[]

In [220]:
len(Flight_Name)

160

In [219]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')

In [63]:
From=[]

In [64]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

In [66]:
len(From)

160

In [67]:
To=[]

In [68]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')

In [70]:
len(To)

160

In [73]:
Time_Taken=[]

In [74]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')

In [76]:
len(Time_Taken)

160

In [87]:
Stopage=[]

In [88]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')

In [203]:
len(Stopage)

160

In [178]:
Price=[]

In [179]:
#scraping the data of Price
try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')

In [182]:
len(Price)

160

In [183]:
Departure_Time=[]

In [184]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')

In [186]:
len(Departure_Time)

160

In [308]:
Arrived_Time=[]

In [309]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [310]:
len(Arrived_Time)

160

In [423]:
#Lets make dataframe
import pandas as pd

In [425]:
Flight_Prediction1=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"04-jan-2023"})

In [ ]:
"Date Of Journey":"04-jan-2023"(flight date),

In [427]:
Flight_Prediction1.to_csv('Flight_Prediction_01')

In [428]:
Flight_Prediction1

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Go First,New Delhi,Mumbai,14h 20m,1 Stop,18:00,08:00,"6,454",04-jan-2023
1,Go First,New Delhi,Mumbai,8h 40m,1 Stop,04:55,09:15,"6,632",04-jan-2023
2,Go First,New Delhi,Mumbai,8h 05m,1 Stop,22:00,10:30\n+ 1 day,"6,755",04-jan-2023
3,Go First,New Delhi,Mumbai,5h 15m,1 Stop,05:00,16:20,"6,873",04-jan-2023
4,Go First,New Delhi,Mumbai,6h 00m,1 Stop,10:40,22:05,"6,873",04-jan-2023
...,...,...,...,...,...,...,...,...,...
155,Air Asia,New Delhi,Mumbai,8h 45m,1 Stop,07:30,19:55,"19,604",04-jan-2023
156,Go First,New Delhi,Mumbai,7h 40m,1 Stop,10:45,18:40,"19,736",04-jan-2023
157,IndiGo,New Delhi,Mumbai,6h 55m,1 Stop,13:00,16:10,"19,814",04-jan-2023
158,IndiGo,New Delhi,Mumbai,9h 00m,1 Stop,09:40,19:30,"21,799",04-jan-2023
159,IndiGo,New Delhi,Mumbai,6h 30m,1 Stop,09:40,18:25,"22,233",04-jan-2023

In [429]:
driver.close()

# NEXT DATA

In [431]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [432]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=05%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1170808134470'

In [433]:
driver.get(url)

In [13]:
# Scraping details of product for which you want
Flight_Name=[]

In [14]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')

In [15]:
len(Flight_Name)

153

In [16]:
From=[]

In [17]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

In [18]:
len(From)

153

In [19]:
To=[]

In [20]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')

In [21]:
len(To)

153

In [22]:
Time_Taken=[]

In [23]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')

In [24]:
len(Time_Taken)

153

In [25]:
Stopage=[]

In [26]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')

In [27]:
len(Stopage)

153

In [28]:
Price=[]

In [29]:
#scraping the data of Price
try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')

In [30]:
len(Price)

153

In [31]:
Departure_Time=[]

In [32]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')

In [33]:
len(Departure_Time)

153

In [34]:
Arrived_Time=[]

In [35]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [36]:
len(Arrived_Time)

153

In [461]:
#Lets make dataframe
import pandas as pd

In [463]:
Flight_Prediction2=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"05-jan-2023"})

In [464]:
Flight_Prediction2.to_csv('Flight_Prediction_02')

In [465]:
driver.close()

# NEXT DATA

In [466]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [467]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=05%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1170808134470'

In [476]:
driver.get(url)

In [10]:
# Scraping details of product for which you want
Flight_Name=[]

In [11]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')

In [12]:
len(Flight_Name)

62

In [13]:
From=[]

In [14]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

In [15]:
len(From)

62

In [16]:
To=[]

In [17]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')

In [18]:
len(To)

62

In [19]:
Time_Taken=[]

In [20]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')

In [21]:
len(Time_Taken)

62

In [22]:
Stopage=[]

In [23]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')

In [24]:
len(Stopage)

62

In [25]:
Price=[]

In [26]:
#scraping the data of Price
try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')

In [27]:
len(Price)

62

In [28]:
Departure_Time=[]

In [29]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')

In [30]:
len(Departure_Time)

62

In [31]:
Arrived_Time=[]

In [32]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [33]:
len(Arrived_Time)

62

In [34]:
#Lets make dataframe
import pandas as pd

In [35]:
Flight_Prediction3=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"06-jan-2023"})

In [37]:
Flight_Prediction3.to_csv('Flight_Prediction_03')

In [38]:
Flight_Prediction3

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"2,489",06-jan-2023
1,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"2,489",06-jan-2023
2,SpiceJet,New Delhi,Jaipur,1h 10m,Non Stop,20:10,21:20,"2,499",06-jan-2023
3,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"2,909",06-jan-2023
4,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,20:30,21:30,"2,909",06-jan-2023
...,...,...,...,...,...,...,...,...,...
57,Vistara,New Delhi,Jaipur,18h 35m,1 Stop,19:00,13:35\n+ 1 day,"17,925",06-jan-2023
58,Air India,New Delhi,Jaipur,16h 35m,2 Stop(s),20:40,13:15\n+ 1 day,"19,558",06-jan-2023
59,Vistara,New Delhi,Jaipur,8h 35m,2 Stop(s),11:00,19:35,"19,920",06-jan-2023
60,Air India,New Delhi,Jaipur,16h 35m,2 Stop(s),20:40,13:15\n+ 1 day,"20,219",06-jan-2023
61,Air India,New Delhi,Jaipur,15h 15m,2 Stop(s),22:00,13:15\n+ 1 day,"20,438",06-jan-2023

In [39]:
driver.close()

# Next Data

In [40]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [41]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=05%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1170808134470'

In [42]:
driver.get(url)

In [43]:
# Scraping details of product for which you want
Flight_Name=[]

In [44]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')

In [45]:
len(Flight_Name)

66

In [46]:
From=[]

In [47]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

In [48]:
len(From)

66

In [49]:
To=[]

In [50]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')

In [51]:
len(To)

66

In [52]:
Time_Taken=[]

In [53]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')

In [54]:
len(Time_Taken)

66

In [55]:
Stopage=[]

In [56]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')

In [57]:
len(Stopage)

66

In [58]:
Price=[]

In [59]:
#scraping the data of Price
try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')

In [60]:
len(Price)

66

In [61]:
Departure_Time=[]

In [62]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')

In [63]:
len(Departure_Time)

66

In [64]:
Arrived_Time=[]

In [65]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [66]:
len(Arrived_Time)

66

In [67]:
#Lets make dataframe
import pandas as pd

In [69]:
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"06-jan-2023"})

In [71]:
Flight_Prediction4.to_csv('Flight_Prediction_04')

In [72]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"1,997",06-jan-2023
1,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"1,998",06-jan-2023
2,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,05:10,06:10,"1,998",06-jan-2023
3,Alliance Air,New Delhi,Jaipur,1h 00m,Non Stop,19:30,20:30,"2,489",06-jan-2023
4,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"2,489",06-jan-2023
...,...,...,...,...,...,...,...,...,...
61,Vistara,New Delhi,Jaipur,28h 50m,2 Stop(s),14:45,19:35\n+ 1 day,"25,062",06-jan-2023
62,Vistara,New Delhi,Jaipur,28h 50m,2 Stop(s),14:45,19:35\n+ 1 day,"25,062",06-jan-2023
63,Vistara,New Delhi,Jaipur,12h 15m,2 Stop(s),07:20,19:35,"28,982",06-jan-2023
64,Vistara,New Delhi,Jaipur,8h 35m,2 Stop(s),11:00,19:35,"29,402",06-jan-2023
65,Vistara,New Delhi,Jaipur,12h 25m,2 Stop(s),07:10,19:35,"33,885",06-jan-2023

In [73]:
driver.close()

# Next Data

In [74]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [75]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=05%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1170808134470'

In [111]:
driver.get(url)

In [98]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [99]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [100]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

67
67
67
67
67
67
67
67

In [86]:
len(To)

134

In [101]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"09-jan-2023"})

In [102]:
Flight_Prediction4.to_csv('Flight_Prediction_05')

In [103]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"1,997",09-jan-2023
1,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"1,997",09-jan-2023
2,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"1,998",09-jan-2023
3,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,05:10,06:10,"1,998",09-jan-2023
4,Alliance Air,New Delhi,Jaipur,1h 00m,Non Stop,06:50,07:50,"2,489",09-jan-2023
...,...,...,...,...,...,...,...,...,...
62,Air India,New Delhi,Jaipur,15h 45m,2 Stop(s),21:30,13:15\n+ 1 day,"17,295",09-jan-2023
63,Vistara,New Delhi,Jaipur,6h 05m,1 Stop,07:30,13:35,"17,607",09-jan-2023
64,Vistara,New Delhi,Jaipur,12h 05m,1 Stop,07:30,19:35,"17,607",09-jan-2023
65,Vistara,New Delhi,Jaipur,14h 00m,2 Stop(s),05:35,19:35,"20,219",09-jan-2023
66,Vistara,New Delhi,Jaipur,12h 15m,2 Stop(s),07:20,19:35,"24,075",09-jan-2023

# NEXT DATA

In [104]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [105]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [106]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

68
68
68
68
68
68
68
68

In [107]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"10-jan-2023"})

In [108]:
Flight_Prediction4.to_csv('Flight_Prediction_06')

In [109]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"1,997",10-jan-2023
1,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"1,997",10-jan-2023
2,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"1,998",10-jan-2023
3,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,05:10,06:10,"1,998",10-jan-2023
4,Alliance Air,New Delhi,Jaipur,1h 00m,Non Stop,06:50,07:50,"2,489",10-jan-2023
...,...,...,...,...,...,...,...,...,...
63,Vistara,New Delhi,Jaipur,20h 00m,2 Stop(s),17:35,13:35\n+ 1 day,"16,187",10-jan-2023
64,Vistara,New Delhi,Jaipur,26h 00m,2 Stop(s),17:35,19:35\n+ 1 day,"16,187",10-jan-2023
65,Vistara,New Delhi,Jaipur,8h 35m,2 Stop(s),11:00,19:35,"16,239",10-jan-2023
66,Vistara,New Delhi,Jaipur,20h 00m,2 Stop(s),17:35,13:35\n+ 1 day,"16,558",10-jan-2023
67,Vistara,New Delhi,Jaipur,14h 00m,2 Stop(s),05:35,19:35,"17,068",10-jan-2023

# Next Data

In [121]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=JAI&destinationCountry=IN&flexi=0&flight_depart_date=11%2F01%2F2023&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=883075972840&version=1.1&viewName=normal'
driver.get(url)

In [122]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [123]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [124]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

68
68
68
68
68
68
68
68

In [125]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"11-jan-2023"})

In [126]:
Flight_Prediction4.to_csv('Flight_Prediction_07')

In [127]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"1,997",11-jan-2023
1,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"1,997",11-jan-2023
2,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,05:10,06:10,"1,998",11-jan-2023
3,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"2,489",11-jan-2023
4,Alliance Air,New Delhi,Jaipur,1h 00m,Non Stop,06:50,07:50,"2,489",11-jan-2023
...,...,...,...,...,...,...,...,...,...
63,Vistara,New Delhi,Jaipur,16h 55m,2 Stop(s),20:40,13:35\n+ 1 day,"16,187",11-jan-2023
64,Vistara,New Delhi,Jaipur,14h 00m,2 Stop(s),05:35,19:35,"16,228",11-jan-2023
65,Vistara,New Delhi,Jaipur,13h 40m,2 Stop(s),05:55,19:35,"16,241",11-jan-2023
66,Air India,New Delhi,Jaipur,15h 45m,2 Stop(s),21:30,13:15\n+ 1 day,"17,295",11-jan-2023
67,Vistara,New Delhi,Jaipur,12h 15m,2 Stop(s),07:20,19:35,"19,286",11-jan-2023

In [128]:
driver.close()

# Next Data

In [129]:
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [138]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=COK&destinationCountry=IN&flexi=0&flight_depart_date=12%2F01%2F2023&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=218419795252&version=1.1&viewName=normal'
driver.get(url)

In [140]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [141]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [142]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

90
90
90
90
90
90
90
90

In [143]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"12-jan-2023"})

In [144]:
Flight_Prediction4.to_csv('Flight_Prediction_08')

In [145]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Kochi,10h 50m,1 Stop,09:30,20:20,"6,711",12-jan-2023
1,Air Asia,New Delhi,Kochi,12h 10m,1 Stop,08:10,20:20,"6,711",12-jan-2023
2,Air Asia,New Delhi,Kochi,14h 35m,1 Stop,21:20,11:55\n+ 1 day,"6,948",12-jan-2023
3,IndiGo,New Delhi,Kochi,7h 40m,1 Stop,22:55,06:35\n+ 1 day,"7,176",12-jan-2023
4,Air Asia,New Delhi,Kochi,5h 55m,1 Stop,16:30,22:25,"7,258",12-jan-2023
...,...,...,...,...,...,...,...,...,...
85,Air India,New Delhi,Kochi,9h 30m,2 Stop(s),09:45,19:15,"18,975",12-jan-2023
86,Air India,New Delhi,Kochi,12h 05m,2 Stop(s),07:10,19:15,"18,975",12-jan-2023
87,Air India,New Delhi,Kochi,13h 45m,2 Stop(s),05:30,19:15,"19,259",12-jan-2023
88,Air India,New Delhi,Kochi,26h 35m,2 Stop(s),04:55,07:30\n+ 1 day,"22,094",12-jan-2023
89,Air India,New Delhi,Kochi,38h 20m,2 Stop(s),04:55,19:15\n+ 1 day,"22,094",12-jan-2023

In [147]:
driver.close()

# Next Data

In [148]:
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [149]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=COK&destinationCountry=IN&flexi=0&flight_depart_date=13%2F01%2F2023&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1672894801586&viewName=normal'
driver.get(url)

In [150]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [151]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [152]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

90
90
90
90
90
90
90
90

In [153]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"13-jan-2023"})

In [154]:
Flight_Prediction4.to_csv('Flight_Prediction_09')

In [155]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Kochi,10h 50m,1 Stop,09:30,20:20,"6,711",13-jan-2023
1,Air Asia,New Delhi,Kochi,12h 10m,1 Stop,08:10,20:20,"6,711",13-jan-2023
2,Air Asia,New Delhi,Kochi,12h 55m,1 Stop,09:30,22:25,"6,711",13-jan-2023
3,Air Asia,New Delhi,Kochi,14h 15m,1 Stop,08:10,22:25,"6,711",13-jan-2023
4,Air Asia,New Delhi,Kochi,5h 55m,1 Stop,16:30,22:25,"7,065",13-jan-2023
...,...,...,...,...,...,...,...,...,...
85,Air India,New Delhi,Kochi,22h 30m,1 Stop,09:00,07:30\n+ 1 day,"22,860",13-jan-2023
86,Air India,New Delhi,Kochi,23h 30m,1 Stop,08:00,07:30\n+ 1 day,"22,860",13-jan-2023
87,Air India,New Delhi,Kochi,24h 30m,1 Stop,07:00,07:30\n+ 1 day,"22,860",13-jan-2023
88,Air India,New Delhi,Kochi,12h 30m,1 Stop,19:00,07:30\n+ 1 day,"24,120",13-jan-2023
89,Air India,New Delhi,Kochi,38h 15m,2 Stop(s),05:00,19:15\n+ 1 day,"29,050",13-jan-2023

In [156]:
driver.close()

In [157]:
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [158]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=COK&destinationCountry=IN&flexi=0&flight_depart_date=14%2F01%2F2023&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1672894994979&viewName=normal'
driver.get(url)

In [161]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [162]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [163]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

88
88
88
88
88
88
88
88

In [164]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"14-jan-2023"})

In [165]:
Flight_Prediction4.to_csv('Flight_Prediction_10')

In [166]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air India,New Delhi,Kochi,3h 05m,Non Stop,04:55,08:00,"7,215",14-jan-2023
1,Air Asia,New Delhi,Kochi,12h 10m,1 Stop,08:10,20:20,"7,304",14-jan-2023
2,Air Asia,New Delhi,Kochi,14h 15m,1 Stop,08:10,22:25,"7,304",14-jan-2023
3,Air Asia,New Delhi,Kochi,8h 50m,1 Stop,21:20,06:10\n+ 1 day,"7,943",14-jan-2023
4,Air Asia,New Delhi,Kochi,10h 50m,1 Stop,09:30,20:20,"8,034",14-jan-2023
...,...,...,...,...,...,...,...,...,...
83,Go First,New Delhi,Kochi,10h 25m,1 Stop,09:00,19:25,"19,514",14-jan-2023
84,Go First,New Delhi,Kochi,13h 25m,1 Stop,06:00,19:25,"19,514",14-jan-2023
85,Air India,New Delhi,Kochi,9h 30m,2 Stop(s),09:45,19:15,"23,385",14-jan-2023
86,Air India,New Delhi,Kochi,12h 05m,2 Stop(s),07:10,19:15,"23,385",14-jan-2023
87,Air India,New Delhi,Kochi,13h 45m,2 Stop(s),05:30,19:15,"32,205",14-jan-2023

# Next Data

In [167]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [168]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [169]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

114
114
114
114
114
114
114
114

In [170]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"6-jan-2023"})

In [171]:
Flight_Prediction4.to_csv('Flight_Prediction_11')

In [172]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air India,Mumbai,Hyderabad,1h 25m,Non Stop,06:00,07:25,"5,103",6-jan-2023
1,IndiGo,Mumbai,Hyderabad,1h 25m,Non Stop,06:50,08:15,"5,103",6-jan-2023
2,Air India,Mumbai,Hyderabad,1h 25m,Non Stop,11:00,12:25,"5,103",6-jan-2023
3,IndiGo,Mumbai,Hyderabad,1h 35m,Non Stop,05:25,07:00,"5,103",6-jan-2023
4,IndiGo,Mumbai,Hyderabad,1h 30m,Non Stop,16:05,17:35,"5,313",6-jan-2023
...,...,...,...,...,...,...,...,...,...
109,Air India,Mumbai,Hyderabad,25h 00m,1 Stop,20:15,21:15\n+ 1 day,"19,068",6-jan-2023
110,Air India,Mumbai,Hyderabad,14h 40m,2 Stop(s),18:00,08:40\n+ 1 day,"19,772",6-jan-2023
111,Air India,Mumbai,Hyderabad,12h 15m,1 Stop,21:05,09:20\n+ 1 day,"22,848",6-jan-2023
112,Air India,Mumbai,Hyderabad,11h 30m,2 Stop(s),12:15,23:45,"26,693",6-jan-2023
113,Air India,Mumbai,Hyderabad,14h 55m,1 Stop,21:05,12:00\n+ 1 day,"27,258",6-jan-2023

# Next Data

In [173]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [174]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [175]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

112
112
112
112
112
112
112
112

In [176]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"7-jan-2023"})

In [177]:
Flight_Prediction4.to_csv('Flight_Prediction_12')

In [178]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air India,Mumbai,Hyderabad,1h 25m,Non Stop,06:00,07:25,"5,103",7-jan-2023
1,IndiGo,Mumbai,Hyderabad,1h 25m,Non Stop,06:50,08:15,"5,103",7-jan-2023
2,IndiGo,Mumbai,Hyderabad,1h 35m,Non Stop,05:25,07:00,"5,103",7-jan-2023
3,Vistara,Mumbai,Hyderabad,1h 25m,Non Stop,06:20,07:45,"5,313",7-jan-2023
4,Vistara,Mumbai,Hyderabad,1h 35m,Non Stop,19:20,20:55,"5,313",7-jan-2023
...,...,...,...,...,...,...,...,...,...
107,Vistara,Mumbai,Hyderabad,10h 30m,1 Stop,06:30,17:00,"16,443",7-jan-2023
108,Vistara,Mumbai,Hyderabad,11h 00m,1 Stop,06:00,17:00,"16,443",7-jan-2023
109,Air India,Mumbai,Hyderabad,15h 30m,1 Stop,05:45,21:15,"19,068",7-jan-2023
110,Air India,Mumbai,Hyderabad,24h 10m,1 Stop,21:05,21:15\n+ 1 day,"22,743",7-jan-2023
111,Air India,Mumbai,Hyderabad,11h 30m,2 Stop(s),12:15,23:45,"25,331",7-jan-2023

# Next DATA

In [179]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [180]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [181]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

111
111
111
111
111
111
111
111

In [183]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"8-jan-2023"})

In [184]:
Flight_Prediction4.to_csv('Flight_Prediction_13')

In [185]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air India,Mumbai,Hyderabad,1h 25m,Non Stop,06:00,07:25,"5,103",8-jan-2023
1,Vistara,Mumbai,Hyderabad,1h 25m,Non Stop,06:20,07:45,"5,313",8-jan-2023
2,IndiGo,Mumbai,Hyderabad,1h 25m,Non Stop,06:50,08:15,"5,313",8-jan-2023
3,IndiGo,Mumbai,Hyderabad,4h 05m,1 Stop,04:50,08:55,"7,323",8-jan-2023
4,IndiGo,Mumbai,Hyderabad,4h 10m,1 Stop,05:35,09:45,"7,492",8-jan-2023
...,...,...,...,...,...,...,...,...,...
106,Vistara,Mumbai,Hyderabad,7h 55m,1 Stop,11:55,19:50,"19,278",8-jan-2023
107,Air India,Mumbai,Hyderabad,6h 00m,1 Stop,13:00,19:00,"19,908",8-jan-2023
108,Air India,Mumbai,Hyderabad,15h 30m,1 Stop,05:45,21:15,"22,743",8-jan-2023
109,Vistara,Mumbai,Hyderabad,7h 25m,1 Stop,12:25,19:50,"22,953",8-jan-2023
110,Air India,Mumbai,Hyderabad,11h 30m,2 Stop(s),12:15,23:45,"29,843",8-jan-2023

# NEXT Data

In [186]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [187]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [189]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

160
160
160
160
160
160
160
160

In [190]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"6-jan-2023"})

In [191]:
Flight_Prediction4.to_csv('Flight_Prediction_14')

In [192]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Bangalore,6h 40m,1 Stop,05:45,12:25,"5,987",6-jan-2023
1,IndiGo,New Delhi,Bangalore,6h 15m,1 Stop,01:55,08:10,"5,988",6-jan-2023
2,IndiGo,New Delhi,Bangalore,8h 10m,1 Stop,11:25,19:35,"5,988",6-jan-2023
3,SpiceJet,New Delhi,Bangalore,2h 45m,Non Stop,22:00,00:45\n+ 1 day,"6,659",6-jan-2023
4,IndiGo,New Delhi,Bangalore,6h 10m,1 Stop,06:10,12:20,"6,737",6-jan-2023
...,...,...,...,...,...,...,...,...,...
155,IndiGo,New Delhi,Bangalore,5h 40m,1 Stop,13:40,19:20,"20,732",6-jan-2023
156,IndiGo,New Delhi,Bangalore,6h 50m,1 Stop,07:45,14:35,"21,232",6-jan-2023
157,Air Asia,New Delhi,Bangalore,7h 50m,1 Stop,07:15,15:05,"23,672",6-jan-2023
158,IndiGo,New Delhi,Bangalore,8h 05m,1 Stop,13:00,21:05,"23,962",6-jan-2023
159,Air Asia,New Delhi,Bangalore,7h 35m,1 Stop,16:55,00:30\n+ 1 day,"29,972",6-jan-2023

# NEXT DATA

In [193]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [194]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [195]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

163
163
163
163
163
163
163
163

In [196]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"7-jan-2023"})

In [197]:
Flight_Prediction4.to_csv('Flight_Prediction_15')

In [198]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air India,New Delhi,Bangalore,2h 45m,Non Stop,06:10,08:55,"5,241",7-jan-2023
1,IndiGo,New Delhi,Bangalore,5h 20m,1 Stop,05:15,10:35,"6,737",7-jan-2023
2,IndiGo,New Delhi,Bangalore,6h 30m,1 Stop,06:30,13:00,"6,737",7-jan-2023
3,IndiGo,New Delhi,Bangalore,6h 50m,1 Stop,17:15,00:05\n+ 1 day,"6,737",7-jan-2023
4,IndiGo,New Delhi,Bangalore,8h 10m,1 Stop,11:25,19:35,"6,737",7-jan-2023
...,...,...,...,...,...,...,...,...,...
158,SpiceJet,New Delhi,Bangalore,21h 15m,1 Stop,19:50,17:05\n+ 1 day,"21,255",7-jan-2023
159,Air Asia,New Delhi,Bangalore,5h 00m,1 Stop,07:10,12:10,"21,509",7-jan-2023
160,Vistara,New Delhi,Bangalore,9h 15m,2 Stop(s),08:20,17:35,"22,965",7-jan-2023
161,Air Asia,New Delhi,Bangalore,7h 50m,1 Stop,07:15,15:05,"26,298",7-jan-2023
162,IndiGo,New Delhi,Bangalore,5h 50m,1 Stop,16:45,22:35,"27,742",7-jan-2023

# Next Data

In [200]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [201]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [202]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

162
162
162
162
162
162
162
162

In [203]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"8-jan-2023"})

In [204]:
Flight_Prediction4.to_csv('Flight_Prediction_16')

In [205]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Go First,New Delhi,Bangalore,2h 50m,Non Stop,05:45,08:35,"8,302",8-jan-2023
1,IndiGo,New Delhi,Bangalore,2h 50m,Non Stop,07:00,09:50,"8,580",8-jan-2023
2,IndiGo,New Delhi,Bangalore,3h 10m,Non Stop,07:55,11:05,"8,580",8-jan-2023
3,Go First,New Delhi,Bangalore,13h 25m,1 Stop,22:00,11:25\n+ 1 day,"8,866",8-jan-2023
4,SpiceJet,New Delhi,Bangalore,2h 35m,Non Stop,20:30,23:05,"9,181",8-jan-2023
...,...,...,...,...,...,...,...,...,...
157,IndiGo,New Delhi,Bangalore,5h 40m,1 Stop,13:40,19:20,"25,676",8-jan-2023
158,Vistara,New Delhi,Bangalore,2h 45m,Non Stop,16:05,18:50,"25,695",8-jan-2023
159,Vistara,New Delhi,Bangalore,2h 50m,Non Stop,14:10,17:00,"25,695",8-jan-2023
160,IndiGo,New Delhi,Bangalore,7h 45m,1 Stop,09:25,17:10,"28,792",8-jan-2023
161,IndiGo,New Delhi,Bangalore,4h 30m,1 Stop,13:40,18:10,"32,467",8-jan-2023

# Next Data

In [206]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [207]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [208]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

167
167
167
167
167
167
167
167

In [209]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"9-jan-2023"})

In [210]:
Flight_Prediction4.to_csv('Flight_Prediction_17')

In [212]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Bangalore,6h 40m,1 Stop,05:45,12:25,"5,987",9-jan-2023
1,Air Asia,New Delhi,Bangalore,7h 50m,1 Stop,23:05,06:55\n+ 1 day,"5,987",9-jan-2023
2,IndiGo,New Delhi,Bangalore,5h 25m,1 Stop,05:15,10:40,"5,988",9-jan-2023
3,IndiGo,New Delhi,Bangalore,5h 25m,1 Stop,18:40,00:05\n+ 1 day,"5,988",9-jan-2023
4,IndiGo,New Delhi,Bangalore,5h 25m,1 Stop,19:45,01:10\n+ 1 day,"5,988",9-jan-2023
...,...,...,...,...,...,...,...,...,...
162,Vistara,New Delhi,Bangalore,2h 45m,Non Stop,16:05,18:50,"15,584",9-jan-2023
163,Air Asia,New Delhi,Bangalore,7h 50m,1 Stop,07:15,15:05,"17,956",9-jan-2023
164,Air Asia,New Delhi,Bangalore,7h 35m,1 Stop,16:55,00:30\n+ 1 day,"18,108",9-jan-2023
165,Go First,New Delhi,Bangalore,13h 40m,1 Stop,05:50,19:30,"18,181",9-jan-2023
166,Air India,New Delhi,Bangalore,2h 55m,Non Stop,13:30,16:25,"18,345",9-jan-2023

# Next Data

In [220]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=MAA&destinationCountry=IN&flight_depart_date=06%2F01%2F2023&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=1144488362753'
driver.get(url)

In [221]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [222]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [223]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

141
141
141
141
141
141
141
141

In [224]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"6-jan-2023"})

In [225]:
Flight_Prediction4.to_csv('Flight_Prediction_18')

In [226]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,SpiceJet,New Delhi,Chennai,2h 35m,Non Stop,06:15,08:50,"6,615",6-jan-2023
1,IndiGo,New Delhi,Chennai,2h 55m,Non Stop,07:10,10:05,"6,616",6-jan-2023
2,IndiGo,New Delhi,Chennai,3h 00m,Non Stop,15:55,18:55,"6,616",6-jan-2023
3,Air India,New Delhi,Chennai,2h 55m,Non Stop,11:50,14:45,"6,690",6-jan-2023
4,Air India,New Delhi,Chennai,2h 55m,Non Stop,19:40,22:35,"6,690",6-jan-2023
...,...,...,...,...,...,...,...,...,...
136,Air India,New Delhi,Chennai,23h 15m,1 Stop,20:15,19:30\n+ 1 day,"21,390",6-jan-2023
137,Air India,New Delhi,Chennai,28h 50m,1 Stop,05:30,10:20\n+ 1 day,"21,462",6-jan-2023
138,Vistara,New Delhi,Chennai,10h 10m,2 Stop(s),14:10,00:20\n+ 1 day,"26,241",6-jan-2023
139,Vistara,New Delhi,Chennai,8h 15m,2 Stop(s),16:05,00:20\n+ 1 day,"27,816",6-jan-2023
140,Air India,New Delhi,Chennai,12h 50m,1 Stop,06:50,19:40,"31,050",6-jan-2023

# NEXT DATA

In [227]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [228]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [229]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

141
141
141
141
141
141
141
141

In [230]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"7-jan-2023"})

In [231]:
Flight_Prediction4.to_csv('Flight_Prediction_19')

In [232]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,SpiceJet,New Delhi,Chennai,2h 40m,Non Stop,18:50,21:30,"6,615",7-jan-2023
1,IndiGo,New Delhi,Chennai,2h 50m,Non Stop,19:20,22:10,"6,616",7-jan-2023
2,IndiGo,New Delhi,Chennai,2h 50m,Non Stop,23:50,02:40\n+ 1 day,"6,616",7-jan-2023
3,IndiGo,New Delhi,Chennai,2h 55m,Non Stop,07:10,10:05,"6,616",7-jan-2023
4,IndiGo,New Delhi,Chennai,2h 55m,Non Stop,08:25,11:20,"6,616",7-jan-2023
...,...,...,...,...,...,...,...,...,...
136,Air India,New Delhi,Chennai,28h 50m,2 Stop(s),05:30,10:20\n+ 1 day,"21,462",7-jan-2023
137,Vistara,New Delhi,Chennai,8h 50m,2 Stop(s),11:00,19:50,"21,495",7-jan-2023
138,Vistara,New Delhi,Chennai,8h 15m,2 Stop(s),16:05,00:20\n+ 1 day,"26,220",7-jan-2023
139,Vistara,New Delhi,Chennai,8h 35m,2 Stop(s),15:45,00:20\n+ 1 day,"28,530",7-jan-2023
140,Air India,New Delhi,Chennai,23h 15m,1 Stop,20:15,19:30\n+ 1 day,"29,790",7-jan-2023

# NEXT DATA

In [233]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [234]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [235]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

137
137
137
137
137
137
137
137

In [236]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"7-jan-2023"})

In [237]:
Flight_Prediction4.to_csv('Flight_Prediction_20')

In [238]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,New Delhi,Chennai,2h 50m,Non Stop,19:20,22:10,"6,616",7-jan-2023
1,IndiGo,New Delhi,Chennai,2h 50m,Non Stop,23:50,02:40\n+ 1 day,"6,616",7-jan-2023
2,IndiGo,New Delhi,Chennai,2h 55m,Non Stop,07:10,10:05,"6,616",7-jan-2023
3,IndiGo,New Delhi,Chennai,2h 55m,Non Stop,08:25,11:20,"6,616",7-jan-2023
4,IndiGo,New Delhi,Chennai,3h 00m,Non Stop,21:10,00:10\n+ 1 day,"6,616",7-jan-2023
...,...,...,...,...,...,...,...,...,...
132,Air India,New Delhi,Chennai,12h 40m,1 Stop,06:50,19:30,"31,050",7-jan-2023
133,Air India,New Delhi,Chennai,7h 20m,1 Stop,12:10,19:30,"32,940",7-jan-2023
134,Vistara,New Delhi,Chennai,8h 50m,2 Stop(s),11:00,19:50,"35,072",7-jan-2023
135,Vistara,New Delhi,Chennai,8h 15m,2 Stop(s),16:05,00:20\n+ 1 day,"37,508",7-jan-2023
136,Vistara,New Delhi,Chennai,10h 10m,2 Stop(s),14:10,00:20\n+ 1 day,"37,508",7-jan-2023

In [240]:
driver.close()

# Next Data

In [241]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [5]:
url="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=06%2F01%2F2023&hb=0&noOfSegments=1&origin=AMD&originCountry=IN&type=O&unique=576508787510&version=1.1&viewName=normal"
driver.get(url)

In [6]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [7]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [8]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

135
135
135
135
135
135
135
135

In [9]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"7-jan-2023"})

In [10]:
Flight_Prediction4.to_csv('Flight_Prediction_21')

In [11]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Kolkata,5h 25m,1 Stop,07:10,12:35,"7,319",7-jan-2023
1,Air Asia,New Delhi,Kolkata,11h 30m,1 Stop,20:40,08:10\n+ 1 day,"7,319",7-jan-2023
2,Air Asia,New Delhi,Kolkata,14h 50m,1 Stop,21:45,12:35\n+ 1 day,"7,319",7-jan-2023
3,Go First,New Delhi,Kolkata,5h 50m,2 Stop(s),06:30,12:20,"7,713",7-jan-2023
4,Go First,New Delhi,Kolkata,7h 20m,1 Stop,02:40,10:00,"7,713",7-jan-2023
...,...,...,...,...,...,...,...,...,...
130,Vistara,New Delhi,Kolkata,10h 45m,2 Stop(s),07:20,18:05,"31,428",7-jan-2023
131,Air India,New Delhi,Kolkata,6h 05m,1 Stop,09:25,15:30,"32,100",7-jan-2023
132,Air India,New Delhi,Kolkata,23h 50m,1 Stop,09:25,09:15\n+ 1 day,"32,100",7-jan-2023
133,Vistara,New Delhi,Kolkata,11h 00m,1 Stop,08:50,19:50,"36,267",7-jan-2023
134,Vistara,New Delhi,Kolkata,9h 15m,1 Stop,08:50,18:05,"38,474",7-jan-2023

In [12]:
driver.close()

# Next Data

In [15]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [17]:
url="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=08%2F01%2F2023&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1672982749498&viewName=normal"
driver.get(url)

In [20]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [21]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [22]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

132
132
132
132
132
132
132
132

In [23]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"8-jan-2023"})

In [24]:
Flight_Prediction4.to_csv('Flight_Prediction_22')

In [25]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Kolkata,4h 40m,1 Stop,10:55,15:35,"7,319",8-jan-2023
1,Air Asia,New Delhi,Kolkata,5h 25m,1 Stop,07:10,12:35,"7,319",8-jan-2023
2,Air Asia,New Delhi,Kolkata,10h 30m,1 Stop,10:55,21:25,"7,319",8-jan-2023
3,Air Asia,New Delhi,Kolkata,11h 30m,1 Stop,20:40,08:10\n+ 1 day,"7,319",8-jan-2023
4,Air Asia,New Delhi,Kolkata,14h 50m,1 Stop,21:45,12:35\n+ 1 day,"7,319",8-jan-2023
...,...,...,...,...,...,...,...,...,...
127,Vistara,New Delhi,Kolkata,7h 00m,1 Stop,12:50,19:50,"31,155",8-jan-2023
128,Vistara,New Delhi,Kolkata,5h 30m,1 Stop,14:20,19:50,"33,255",8-jan-2023
129,Vistara,New Delhi,Kolkata,8h 50m,2 Stop(s),11:00,19:50,"34,725",8-jan-2023
130,Vistara,New Delhi,Kolkata,12h 40m,2 Stop(s),07:10,19:50,"37,770",8-jan-2023
131,Vistara,New Delhi,Kolkata,10h 45m,2 Stop(s),07:20,18:05,"45,750",8-jan-2023

In [26]:
driver.close()

# Next Data

In [27]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [28]:
url="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=08%2F01%2F2023&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1672982749498&viewName=normal"
driver.get(url)

In [29]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [30]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [31]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

137
137
137
137
137
137
137
137

In [32]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"9-jan-2023"})

In [33]:
Flight_Prediction4.to_csv('Flight_Prediction_23')

In [34]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,New Delhi,Kolkata,4h 45m,1 Stop,14:55,19:40,"7,319",9-jan-2023
1,Air Asia,New Delhi,Kolkata,5h 25m,1 Stop,07:10,12:35,"7,319",9-jan-2023
2,Air Asia,New Delhi,Kolkata,11h 25m,1 Stop,15:05,02:30\n+ 1 day,"7,319",9-jan-2023
3,Air Asia,New Delhi,Kolkata,11h 30m,1 Stop,20:40,08:10\n+ 1 day,"7,319",9-jan-2023
4,Air Asia,New Delhi,Kolkata,14h 50m,1 Stop,21:45,12:35\n+ 1 day,"7,319",9-jan-2023
...,...,...,...,...,...,...,...,...,...
132,Vistara,New Delhi,Kolkata,8h 35m,1 Stop,09:30,18:05,"25,695",9-jan-2023
133,Vistara,New Delhi,Kolkata,9h 05m,1 Stop,09:00,18:05,"25,695",9-jan-2023
134,Vistara,New Delhi,Kolkata,10h 35m,1 Stop,07:30,18:05,"27,270",9-jan-2023
135,Vistara,New Delhi,Kolkata,11h 10m,2 Stop(s),06:55,18:05,"36,678",9-jan-2023
136,Air India,New Delhi,Kolkata,18h 30m,1 Stop,16:10,10:40\n+ 1 day,"39,839",9-jan-2023

# Next Data

In [35]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [36]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [37]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

134
134
134
134
134
134
134
134

In [38]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"10-jan-2023"})

In [39]:
Flight_Prediction4.to_csv('Flight_Prediction_24')

In [40]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Kolkata,4h 40m,1 Stop,10:55,15:35,"7,319",10-jan-2023
1,IndiGo,New Delhi,Kolkata,4h 45m,1 Stop,14:55,19:40,"7,319",10-jan-2023
2,Air Asia,New Delhi,Kolkata,5h 25m,1 Stop,07:10,12:35,"7,319",10-jan-2023
3,IndiGo,New Delhi,Kolkata,6h 10m,1 Stop,13:30,19:40,"7,319",10-jan-2023
4,Air Asia,New Delhi,Kolkata,10h 30m,1 Stop,10:55,21:25,"7,319",10-jan-2023
...,...,...,...,...,...,...,...,...,...
129,Vistara,New Delhi,Kolkata,8h 00m,1 Stop,08:50,16:50,"20,025",10-jan-2023
130,IndiGo,New Delhi,Kolkata,4h 55m,1 Stop,07:45,12:40,"20,129",10-jan-2023
131,Vistara,New Delhi,Kolkata,14h 40m,1 Stop,19:00,09:40\n+ 1 day,"20,445",10-jan-2023
132,Vistara,New Delhi,Kolkata,12h 20m,2 Stop(s),21:20,09:40\n+ 1 day,"26,357",10-jan-2023
133,Air India,New Delhi,Kolkata,18h 30m,1 Stop,16:10,10:40\n+ 1 day,"28,950",10-jan-2023

In [41]:
driver.close()

# Next Data

In [45]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [46]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=PAT&destinationCountry=IN&flexi=0&flight_depart_date=07%2F01%2F2023&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1114020979709&version=1.1&viewName=normal'
driver.get(url)

In [47]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [48]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [49]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

104
104
104
104
104
104
104
104

In [50]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"07-jan-2023"})

In [51]:
Flight_Prediction4.to_csv('Flight_Prediction_25')

In [52]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Mumbai,Patna,2h 20m,Non Stop,18:05,20:25,"6,677",07-jan-2023
1,Go First,Mumbai,Patna,2h 25m,Non Stop,11:05,13:30,"6,677",07-jan-2023
2,Go First,Mumbai,Patna,6h 05m,1 Stop,05:30,11:35,"7,703",07-jan-2023
3,Go First,Mumbai,Patna,6h 40m,1 Stop,05:50,12:30,"7,703",07-jan-2023
4,Go First,Mumbai,Patna,10h 10m,1 Stop,09:55,20:05,"7,703",07-jan-2023
...,...,...,...,...,...,...,...,...,...
99,Vistara,Mumbai,Patna,12h 25m,2 Stop(s),05:40,18:05,"22,007",07-jan-2023
100,Vistara,Mumbai,Patna,11h 45m,2 Stop(s),06:20,18:05,"22,742",07-jan-2023
101,Vistara,Mumbai,Patna,19h 15m,2 Stop(s),22:50,18:05\n+ 1 day,"23,509",07-jan-2023
102,Vistara,Mumbai,Patna,19h 25m,2 Stop(s),22:40,18:05\n+ 1 day,"27,607",07-jan-2023
103,Vistara,Mumbai,Patna,23h 35m,1 Stop,18:30,18:05\n+ 1 day,"33,527",07-jan-2023

# Next DATA

In [53]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [54]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [55]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

104
104
104
104
104
104
104
104

In [56]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"08-jan-2023"})

In [57]:
Flight_Prediction4.to_csv('Flight_Prediction_26')

In [58]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Mumbai,Patna,2h 20m,Non Stop,18:05,20:25,"6,677",08-jan-2023
1,Go First,Mumbai,Patna,2h 25m,Non Stop,11:20,13:45,"6,677",08-jan-2023
2,Go First,Mumbai,Patna,11h 30m,1 Stop,08:45,20:15,"7,703",08-jan-2023
3,Go First,Mumbai,Patna,12h 45m,1 Stop,23:45,12:30\n+ 1 day,"7,703",08-jan-2023
4,Go First,Mumbai,Patna,13h 35m,1 Stop,22:55,12:30\n+ 1 day,"7,703",08-jan-2023
...,...,...,...,...,...,...,...,...,...
99,Vistara,Mumbai,Patna,11h 30m,2 Stop(s),06:35,18:05,"24,528",08-jan-2023
100,Vistara,Mumbai,Patna,12h 25m,2 Stop(s),05:40,18:05,"26,943",08-jan-2023
101,Vistara,Mumbai,Patna,11h 45m,2 Stop(s),06:20,18:05,"27,321",08-jan-2023
102,Vistara,Mumbai,Patna,11h 30m,2 Stop(s),06:35,18:05,"28,447",08-jan-2023
103,Vistara,Mumbai,Patna,12h 25m,2 Stop(s),05:40,18:05,"29,043",08-jan-2023

# Next Data

In [59]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [60]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [61]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

102
102
102
102
102
102
102
102

In [63]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"09-jan-2023"})

In [64]:
Flight_Prediction4.to_csv('Flight_Prediction_27')

In [65]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Mumbai,Patna,2h 20m,Non Stop,18:05,20:25,"6,677",09-jan-2023
1,Go First,Mumbai,Patna,2h 25m,Non Stop,11:20,13:45,"6,677",09-jan-2023
2,Air India,Mumbai,Patna,2h 40m,Non Stop,11:15,13:55,"6,678",09-jan-2023
3,Go First,Mumbai,Patna,5h 50m,1 Stop,05:45,11:35,"7,703",09-jan-2023
4,Go First,Mumbai,Patna,6h 40m,1 Stop,05:50,12:30,"7,703",09-jan-2023
...,...,...,...,...,...,...,...,...,...
97,Vistara,Mumbai,Patna,11h 30m,2 Stop(s),06:35,18:05,"21,726",09-jan-2023
98,Vistara,Mumbai,Patna,11h 05m,2 Stop(s),07:00,18:05,"25,263",09-jan-2023
99,Vistara,Mumbai,Patna,11h 05m,2 Stop(s),07:00,18:05,"25,263",09-jan-2023
100,Vistara,Mumbai,Patna,12h 05m,2 Stop(s),06:00,18:05,"27,048",09-jan-2023
101,Vistara,Mumbai,Patna,12h 05m,2 Stop(s),06:00,18:05,"27,048",09-jan-2023

In [66]:
160+150+62+66+67+68+90+90+88+114+112+11+160+163+167+141+141+137+135+132+137+134+104+104+102

2835

In [67]:
driver.close()

# Next Data

In [68]:
#Lets Scrape Next Data
#First Connect to web driver 

driver = webdriver.Edge(r"D:\edgedriver_win64\msedgedriver.exe")
driver

In [69]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=JAI&destinationCountry=IN&flexi=0&flight_depart_date=07%2F01%2F2023&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=952903898801&version=1.1&viewName=normal'
driver.get(url)

In [73]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [74]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [75]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

54
54
54
54
54
54
54
54

In [76]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"07-jan-2023"})

In [77]:
Flight_Prediction4.to_csv('Flight_Prediction_28')

In [78]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"1,767",07-jan-2023
1,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"1,997",07-jan-2023
2,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"1,998",07-jan-2023
3,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,05:10,06:10,"1,998",07-jan-2023
4,Alliance Air,New Delhi,Jaipur,1h 00m,Non Stop,07:30,08:30,"2,070",07-jan-2023
5,SpiceJet,New Delhi,Jaipur,1h 10m,Non Stop,20:10,21:20,"2,200",07-jan-2023
6,Alliance Air,New Delhi,Jaipur,1h 00m,Non Stop,19:30,20:30,"2,489",07-jan-2023
7,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,20:30,21:30,"3,329",07-jan-2023
8,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,07:45,08:45,"8,789",07-jan-2023
9,Vistara,New Delhi,Jaipur,13h 50m,1 Stop,05:45,19:35,"9,675",07-jan-2023
10,Vistara,New Delhi,Jaipur,7h 55m,1 Stop,11:40,19:35,"11,040",07-jan-2023
11,Vistara,New Delhi,Jaipur,9h 15m,1 Stop,10:20,19:35,"11,040",07-jan-2023
12,Vistara,New Delhi,Jaipur,10h 05m,1 Stop,09:30,19:35,"11,040",07-jan-2023
13,Vistara,New Delhi,Jaipur,10h 45m,1 Stop,08:50,19:35,"11,040",07-jan-2023
14,Vistara,New Delhi,Jaipur,7h 50m,1 Stop,05:45,13:35,"11,831",07-jan-2023
15,Vistara,New Delhi,Jaipur,12h 05m,1 Stop,07:30,19:35,"12,301",07-jan-2023
16,IndiGo,New Delhi,Jaipur,0h 45m,Non Stop,13:00,13:45,"13,199",07-jan-2023
17,Vistara,New Delhi,Jaipur,22h 15m,2 Stop(s),21:20,19:35\n+ 1 day,"13,699",07-jan-2023
18,Vistara,New Delhi,Jaipur,5h 15m,1 Stop,14:20,19:35,"13,876",07-jan-2023
19,Vistara,New Delhi,Jaipur,6h 45m,1 Stop,12:50,19:35,"13,876",07-jan-2023
20,Vistara,New Delhi,Jaipur,21h 55m,1 Stop,21:40,19:35\n+ 1 day,"13,935",07-jan-2023
21,Vistara,New Delhi,Jaipur,23h 50m,1 Stop,19:45,19:35\n+ 1 day,"13,935",07-jan-2023
22,Vistara,New Delhi,Jaipur,24h 35m,1 Stop,19:00,19:35\n+ 1 day,"13,935",07-jan-2023
23,Vistara,New Delhi,Jaipur,25h 50m,1 Stop,17:45,19:35\n+ 1 day,"13,935",07-jan-2023
24,Vistara,New Delhi,Jaipur,6h 05m,1 Stop,07:30,13:35,"14,457",07-jan-2023
25,Vistara,New Delhi,Jaipur,27h 00m,1 Stop,16:35,19:35\n+ 1 day,"15,195",07-jan-2023
26,Vistara,New Delhi,Jaipur,8h 35m,2 Stop(s),11:00,19:35,"15,343",07-jan-2023
27,Vistara,New Delhi,Jaipur,25h 35m,2 Stop(s),18:00,19:35\n+ 1 day,"15,647",07-jan-2023
28,Vistara,New Delhi,Jaipur,22h 55m,2 Stop(s),20:40,19:35\n+ 1 day,"15,707",07-jan-2023
29,Go First,New Delhi,Jaipur,15h 50m,1 Stop,20:10,12:00\n+ 1 day,"15,997",07-jan-2023
30,Vistara,New Delhi,Jaipur,36h 15m,2 Stop(s),07:20,19:35\n+ 1 day,"16,022",07-jan-2023
31,Vistara,New Delhi,Jaipur,14h 00m,2 Stop(s),05:35,19:35,"16,202",07-jan-2023
32,Vistara,New Delhi,Jaipur,26h 00m,2 Stop(s),17:35,19:35\n+ 1 day,"16,442",07-jan-2023
33,Vistara,New Delhi,Jaipur,28h 50m,2 Stop(s),14:45,19:35\n+ 1 day,"17,072",07-jan-2023
34,Air India,New Delhi,Jaipur,5h 15m,1 Stop,08:00,13:15,"17,400",07-jan-2023
35,Air India,New Delhi,Jaipur,6h 15m,1 Stop,07:00,13:15,"17,400",07-jan-2023
36,Vistara,New Delhi,Jaipur,33h 15m,2 Stop(s),10:20,19:35\n+ 1 day,"17,912",07-jan-2023
37,Vistara,New Delhi,Jaipur,15h 55m,1 Stop,21:40,13:35\n+ 1 day,"18,030",07-jan-2023
38,Vistara,New Delhi,Jaipur,17h 50m,1 Stop,19:45,13:35\n+ 1 day,"18,030",07-jan-2023
39,Vistara,New Delhi,Jaipur,18h 35m,1 Stop,19:00,13:35\n+ 1 day,"18,030",07-jan-2023
40,Vistara,New Delhi,Jaipur,19h 50m,1 Stop,17:45,13:35\n+ 1 day,"18,030",07-jan-2023
41,Vistara,New Delhi,Jaipur,22h 05m,1 Stop,15:30,13:35\n+ 1 day,"18,030",07-jan-2023
42,Vistara,New Delhi,Jaipur,21h 00m,1 Stop,16:35,13:35\n+ 1 day,"19,290",07-jan-2023
43,Air India,New Delhi,Jaipur,8h 30m,2 Stop(s),04:45,13:15,"20,171",07-jan-2023
44,Air India,New Delhi,Jaipur,14h 45m,1 Stop,22:30,13:15\n+ 1 day,"20,865",07-jan-2023
45,Air India,New Delhi,Jaipur,15h 55m,1 Stop,21:20,13:15\n+ 1 day,"20,865",07-jan-2023
46,Air India,New Delhi,Jaipur,17h 15m,1 Stop,20:00,13:15\n+ 1 day,"20,865",07-jan-2023
47,Air India,New Delhi,Jaipur,18h 15m,1 Stop,19:00,13:15\n+ 1 day,"20,865",07-jan-2023
48,Air India,New Delhi,Jaipur,19h 40m,1 Stop,17:35,13:15\n+ 1 day,"20,865",07-jan-2023
49,Air India,New Delhi,Jaipur,23h 15m,1 Stop,14:00,13:15\n+ 1 day,"20,865",07-jan-2023
50,Vistara,New Delhi,Jaipur,12h 15m,2 Stop(s),07:20,19:35,"22,968",07-jan-2023
51,Air India,New Delhi,Jaipur,16h 35m,2 Stop(s),20:40,13:15\n+ 1 day,"24,751",07-jan-2023
52,Vistara,New Delhi,Jaipur,13h 40m,2 Stop(s),05:55,19:35,"26,806",07-jan-2023
53,Air India,New Delhi,Jaipur,16h 35m,2 Stop(s),20:40,13:15\n+ 1 day,"26,893",07-jan-2023

# NEXT DATA

In [79]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [80]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [81]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

53
53
53
53
53
53
53
53

In [82]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"08-jan-2023"})

In [83]:
Flight_Prediction4.to_csv('Flight_Prediction_29')

In [84]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"1,767",08-jan-2023
1,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"1,997",08-jan-2023
2,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,05:10,06:10,"1,998",08-jan-2023
3,SpiceJet,New Delhi,Jaipur,1h 10m,Non Stop,20:10,21:20,"2,200",08-jan-2023
4,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"2,489",08-jan-2023
5,Alliance Air,New Delhi,Jaipur,1h 00m,Non Stop,06:50,07:50,"2,489",08-jan-2023
6,Alliance Air,New Delhi,Jaipur,1h 00m,Non Stop,19:30,20:30,"2,489",08-jan-2023
7,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,20:30,21:30,"3,329",08-jan-2023
8,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,07:45,08:45,"9,419",08-jan-2023
9,Air India,New Delhi,Jaipur,28h 15m,1 Stop,09:00,13:15\n+ 1 day,"10,680",08-jan-2023
10,Air India,New Delhi,Jaipur,14h 45m,1 Stop,22:30,13:15\n+ 1 day,"12,045",08-jan-2023
11,Air India,New Delhi,Jaipur,15h 55m,1 Stop,21:20,13:15\n+ 1 day,"12,045",08-jan-2023
12,Air India,New Delhi,Jaipur,18h 15m,1 Stop,19:00,13:15\n+ 1 day,"12,045",08-jan-2023
13,Air India,New Delhi,Jaipur,19h 25m,1 Stop,17:50,13:15\n+ 1 day,"12,045",08-jan-2023
14,Air India,New Delhi,Jaipur,27h 15m,1 Stop,10:00,13:15\n+ 1 day,"12,045",08-jan-2023
15,IndiGo,New Delhi,Jaipur,0h 45m,Non Stop,13:00,13:45,"13,199",08-jan-2023
16,Air India,New Delhi,Jaipur,23h 15m,1 Stop,14:00,13:15\n+ 1 day,"13,305",08-jan-2023
17,Vistara,New Delhi,Jaipur,24h 35m,1 Stop,19:00,19:35\n+ 1 day,"13,511",08-jan-2023
18,Vistara,New Delhi,Jaipur,18h 35m,1 Stop,19:00,13:35\n+ 1 day,"13,830",08-jan-2023
19,Vistara,New Delhi,Jaipur,24h 55m,2 Stop(s),18:40,19:35\n+ 1 day,"14,141",08-jan-2023
20,Vistara,New Delhi,Jaipur,18h 55m,2 Stop(s),18:40,13:35\n+ 1 day,"14,510",08-jan-2023
21,Vistara,New Delhi,Jaipur,24h 55m,2 Stop(s),18:40,19:35\n+ 1 day,"15,025",08-jan-2023
22,Vistara,New Delhi,Jaipur,10h 05m,1 Stop,09:30,19:35,"15,195",08-jan-2023
23,Vistara,New Delhi,Jaipur,10h 45m,1 Stop,08:50,19:35,"15,195",08-jan-2023
24,Vistara,New Delhi,Jaipur,12h 05m,1 Stop,07:30,19:35,"15,195",08-jan-2023
25,Vistara,New Delhi,Jaipur,30h 25m,2 Stop(s),07:10,13:35\n+ 1 day,"15,980",08-jan-2023
26,Vistara,New Delhi,Jaipur,27h 15m,1 Stop,10:20,13:35\n+ 1 day,"16,350",08-jan-2023
27,Vistara,New Delhi,Jaipur,13h 40m,2 Stop(s),05:55,19:35,"16,454",08-jan-2023
28,Vistara,New Delhi,Jaipur,9h 15m,1 Stop,10:20,19:35,"16,770",08-jan-2023
29,Air India,New Delhi,Jaipur,15h 15m,2 Stop(s),22:00,13:15\n+ 1 day,"16,868",08-jan-2023
30,Vistara,New Delhi,Jaipur,27h 00m,1 Stop,16:35,19:35\n+ 1 day,"17,607",08-jan-2023
31,Vistara,New Delhi,Jaipur,21h 00m,1 Stop,16:35,13:35\n+ 1 day,"17,925",08-jan-2023
32,Vistara,New Delhi,Jaipur,7h 55m,1 Stop,11:40,19:35,"18,345",08-jan-2023
33,Vistara,New Delhi,Jaipur,6h 05m,1 Stop,07:30,13:35,"19,290",08-jan-2023
34,Air India,New Delhi,Jaipur,5h 15m,1 Stop,08:00,13:15,"19,500",08-jan-2023
35,Air India,New Delhi,Jaipur,6h 15m,1 Stop,07:00,13:15,"19,500",08-jan-2023
36,Go First,New Delhi,Jaipur,15h 50m,1 Stop,20:10,12:00\n+ 1 day,"19,674",08-jan-2023
37,Vistara,New Delhi,Jaipur,21h 55m,1 Stop,21:40,19:35\n+ 1 day,"19,707",08-jan-2023
38,Vistara,New Delhi,Jaipur,23h 50m,1 Stop,19:45,19:35\n+ 1 day,"19,707",08-jan-2023
39,Vistara,New Delhi,Jaipur,25h 50m,1 Stop,17:45,19:35\n+ 1 day,"19,707",08-jan-2023
40,Vistara,New Delhi,Jaipur,15h 55m,1 Stop,21:40,13:35\n+ 1 day,"20,025",08-jan-2023
41,Vistara,New Delhi,Jaipur,17h 50m,1 Stop,19:45,13:35\n+ 1 day,"20,025",08-jan-2023
42,Vistara,New Delhi,Jaipur,19h 50m,1 Stop,17:45,13:35\n+ 1 day,"20,025",08-jan-2023
43,Vistara,New Delhi,Jaipur,22h 05m,1 Stop,15:30,13:35\n+ 1 day,"20,025",08-jan-2023
44,Vistara,New Delhi,Jaipur,5h 15m,1 Stop,14:20,19:35,"20,445",08-jan-2023
45,Vistara,New Delhi,Jaipur,6h 45m,1 Stop,12:50,19:35,"20,445",08-jan-2023
46,Vistara,New Delhi,Jaipur,8h 35m,2 Stop(s),11:00,19:35,"21,388",08-jan-2023
47,Air India,New Delhi,Jaipur,8h 30m,2 Stop(s),04:45,13:15,"23,037",08-jan-2023
48,Air India,New Delhi,Jaipur,16h 35m,2 Stop(s),20:40,13:15\n+ 1 day,"25,821",08-jan-2023
49,Air India,New Delhi,Jaipur,17h 35m,2 Stop(s),19:40,13:15\n+ 1 day,"25,821",08-jan-2023
50,Vistara,New Delhi,Jaipur,12h 25m,2 Stop(s),07:10,19:35,"26,850",08-jan-2023
51,Air India,New Delhi,Jaipur,16h 35m,2 Stop(s),20:40,13:15\n+ 1 day,"31,544",08-jan-2023
52,Vistara,New Delhi,Jaipur,12h 15m,2 Stop(s),07:20,19:35,"31,890",08-jan-2023

# NEXT DATA

In [85]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [86]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [87]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

68
68
68
68
68
68
68
68

In [88]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"09-jan-2023"})

In [89]:
Flight_Prediction4.to_csv('Flight_Prediction_29')

In [90]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"1,767",09-jan-2023
1,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"1,997",09-jan-2023
2,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,05:10,06:10,"1,998",09-jan-2023
3,SpiceJet,New Delhi,Jaipur,1h 10m,Non Stop,20:10,21:20,"2,200",09-jan-2023
4,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"2,489",09-jan-2023
...,...,...,...,...,...,...,...,...,...
63,Vistara,New Delhi,Jaipur,20h 00m,2 Stop(s),17:35,13:35\n+ 1 day,"20,337",09-jan-2023
64,Vistara,New Delhi,Jaipur,26h 00m,2 Stop(s),17:35,19:35\n+ 1 day,"20,337",09-jan-2023
65,Vistara,New Delhi,Jaipur,20h 00m,2 Stop(s),17:35,13:35\n+ 1 day,"21,072",09-jan-2023
66,Vistara,New Delhi,Jaipur,27h 15m,2 Stop(s),10:20,13:35\n+ 1 day,"23,390",09-jan-2023
67,Vistara,New Delhi,Jaipur,12h 40m,2 Stop(s),06:55,19:35,"26,175",09-jan-2023

# NEXT DATA

In [91]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [92]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [93]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

69
69
69
69
69
69
69
69

In [94]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"10-jan-2023"})

In [95]:
Flight_Prediction4.to_csv('Flight_Prediction_30')

In [96]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,Air Asia,New Delhi,Jaipur,1h 10m,Non Stop,04:55,06:05,"1,767",10-jan-2023
1,Air Asia,New Delhi,Jaipur,1h 00m,Non Stop,20:25,21:25,"1,997",10-jan-2023
2,IndiGo,New Delhi,Jaipur,0h 55m,Non Stop,22:45,23:40,"1,998",10-jan-2023
3,IndiGo,New Delhi,Jaipur,1h 00m,Non Stop,05:10,06:10,"1,998",10-jan-2023
4,SpiceJet,New Delhi,Jaipur,1h 10m,Non Stop,20:10,21:20,"2,200",10-jan-2023
...,...,...,...,...,...,...,...,...,...
64,Vistara,New Delhi,Jaipur,25h 50m,1 Stop,17:45,19:35\n+ 1 day,"17,607",10-jan-2023
65,Vistara,New Delhi,Jaipur,6h 05m,1 Stop,07:30,13:35,"19,707",10-jan-2023
66,Vistara,New Delhi,Jaipur,12h 05m,1 Stop,07:30,19:35,"19,707",10-jan-2023
67,Vistara,New Delhi,Jaipur,24h 55m,2 Stop(s),18:40,19:35\n+ 1 day,"19,917",10-jan-2023
68,Vistara,New Delhi,Jaipur,32h 25m,2 Stop(s),11:10,19:35\n+ 1 day,"22,542",10-jan-2023

# NEXT DATA

In [98]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=DEL&destinationCountry=IN&flexi=0&flight_depart_date=07%2F01%2F2023&hb=0&noOfSegments=1&origin=IDR&originCountry=IN&type=O&unique=1152161030173&version=1.1&viewName=normal'
driver.get(url)

In [99]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [100]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [101]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

67
67
67
67
67
67
67
67

In [102]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"07-jan-2023"})

In [103]:
Flight_Prediction4.to_csv('Flight_Prediction_31')

In [104]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Indore,New Delhi,1h 25m,Non Stop,07:20,08:45,"4,478",07-jan-2023
1,Vistara,Indore,New Delhi,1h 15m,Non Stop,08:10,09:25,"5,318",07-jan-2023
2,IndiGo,Indore,New Delhi,1h 35m,Non Stop,22:50,00:25\n+ 1 day,"5,632",07-jan-2023
3,IndiGo,Indore,New Delhi,1h 25m,Non Stop,18:50,20:15,"5,737",07-jan-2023
4,IndiGo,Indore,New Delhi,1h 30m,Non Stop,11:30,13:00,"5,737",07-jan-2023
...,...,...,...,...,...,...,...,...,...
62,IndiGo,Indore,New Delhi,5h 35m,1 Stop,07:50,13:25,"21,825",07-jan-2023
63,Air India,Indore,New Delhi,16h 40m,2 Stop(s),16:35,09:15\n+ 1 day,"23,693",07-jan-2023
64,Air India,Indore,New Delhi,16h 40m,2 Stop(s),16:35,09:15\n+ 1 day,"23,693",07-jan-2023
65,Vistara,Indore,New Delhi,17h 40m,2 Stop(s),15:40,09:20\n+ 1 day,"26,065",07-jan-2023
66,Vistara,Indore,New Delhi,5h 00m,1 Stop,15:40,20:40,"32,271",07-jan-2023

# NEXT DATA

In [105]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [106]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [107]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

66
66
66
66
66
66
66
66

In [108]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"08-jan-2023"})

In [109]:
Flight_Prediction4.to_csv('Flight_Prediction_32')

In [110]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Indore,New Delhi,1h 25m,Non Stop,07:20,08:45,"4,478",08-jan-2023
1,Vistara,Indore,New Delhi,1h 15m,Non Stop,08:10,09:25,"5,318",08-jan-2023
2,IndiGo,Indore,New Delhi,1h 30m,Non Stop,11:30,13:00,"8,047",08-jan-2023
3,IndiGo,Indore,New Delhi,9h 10m,1 Stop,08:05,17:15,"8,706",08-jan-2023
4,IndiGo,Indore,New Delhi,5h 55m,1 Stop,17:00,22:55,"9,161",08-jan-2023
...,...,...,...,...,...,...,...,...,...
61,Vistara,Indore,New Delhi,8h 05m,2 Stop(s),15:40,23:45,"27,262",08-jan-2023
62,Vistara,Indore,New Delhi,8h 25m,2 Stop(s),15:40,00:05\n+ 1 day,"27,609",08-jan-2023
63,Air India,Indore,New Delhi,16h 20m,2 Stop(s),16:35,08:55\n+ 1 day,"29,332",08-jan-2023
64,Vistara,Indore,New Delhi,8h 30m,1 Stop,15:40,00:10\n+ 1 day,"32,272",08-jan-2023
65,Vistara,Indore,New Delhi,17h 40m,2 Stop(s),15:40,09:20\n+ 1 day,"38,455",08-jan-2023

# NEXT DATA

In [111]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [112]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [113]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

62
62
62
62
62
62
62
62

In [114]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"09-jan-2023"})

In [115]:
Flight_Prediction4.to_csv('Flight_Prediction_33')

In [116]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Indore,New Delhi,1h 25m,Non Stop,07:20,08:45,"5,527",09-jan-2023
1,Vistara,Indore,New Delhi,1h 15m,Non Stop,08:10,09:25,"5,528",09-jan-2023
2,IndiGo,Indore,New Delhi,1h 35m,Non Stop,22:50,00:25\n+ 1 day,"5,632",09-jan-2023
3,IndiGo,Indore,New Delhi,1h 30m,Non Stop,11:30,13:00,"8,467",09-jan-2023
4,IndiGo,Indore,New Delhi,11h 40m,1 Stop,21:35,09:15\n+ 1 day,"8,614",09-jan-2023
...,...,...,...,...,...,...,...,...,...
57,IndiGo,Indore,New Delhi,5h 05m,1 Stop,06:05,11:10,"17,533",09-jan-2023
58,Vistara,Indore,New Delhi,1h 35m,Non Stop,20:55,22:30,"18,563",09-jan-2023
59,Vistara,Indore,New Delhi,8h 25m,2 Stop(s),15:40,00:05\n+ 1 day,"18,705",09-jan-2023
60,Air India,Indore,New Delhi,16h 40m,2 Stop(s),16:35,09:15\n+ 1 day,"21,173",09-jan-2023
61,Air India,Indore,New Delhi,16h 40m,2 Stop(s),16:35,09:15\n+ 1 day,"21,173",09-jan-2023

# NEXT DATA

In [117]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [118]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [119]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

68
68
68
68
68
68
68
68

In [120]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"10-jan-2023"})

In [121]:
Flight_Prediction4.to_csv('Flight_Prediction_34')

In [122]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Indore,New Delhi,1h 30m,Non Stop,11:30,13:00,"4,478",10-jan-2023
1,IndiGo,Indore,New Delhi,1h 25m,Non Stop,07:20,08:45,"5,527",10-jan-2023
2,Alliance Air,Indore,New Delhi,4h 00m,1 Stop,16:00,20:00,"5,527",10-jan-2023
3,IndiGo,Indore,New Delhi,1h 35m,Non Stop,22:50,00:25\n+ 1 day,"6,262",10-jan-2023
4,Vistara,Indore,New Delhi,1h 15m,Non Stop,08:10,09:25,"6,368",10-jan-2023
...,...,...,...,...,...,...,...,...,...
63,Vistara,Indore,New Delhi,6h 15m,1 Stop,15:40,21:55,"18,757",10-jan-2023
64,Vistara,Indore,New Delhi,8h 25m,2 Stop(s),15:40,00:05\n+ 1 day,"19,828",10-jan-2023
65,Air India,Indore,New Delhi,16h 40m,2 Stop(s),16:35,09:15\n+ 1 day,"21,593",10-jan-2023
66,Air India,Indore,New Delhi,16h 40m,2 Stop(s),16:35,09:15\n+ 1 day,"21,593",10-jan-2023
67,Vistara,Indore,New Delhi,17h 40m,2 Stop(s),15:40,09:20\n+ 1 day,"21,802",10-jan-2023

# NEXT DATA

In [130]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=RPR&destinationCountry=IN&flexi=0&flight_depart_date=07%2F01%2F2023&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=222830016237&version=1.1&viewName=normal'
driver.get(url)

In [131]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [135]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [136]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

31
31
31
31
31
31
31
31

In [137]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"07-jan-2023"})

In [138]:
Flight_Prediction4.to_csv('Flight_Prediction_35')

In [139]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Kolkata,Raipur,5h 35m,1 Stop,05:25,11:00,"6,932",07-jan-2023
1,IndiGo,Kolkata,Raipur,11h 45m,1 Stop,23:15,11:00\n+ 1 day,"7,803",07-jan-2023
2,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,07:35,09:10,"8,233",07-jan-2023
3,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,15:15,16:50,"8,233",07-jan-2023
4,IndiGo,Kolkata,Raipur,2h 20m,Non Stop,17:10,19:30,"8,233",07-jan-2023
5,IndiGo,Kolkata,Raipur,8h 45m,1 Stop,11:05,19:50,"8,803",07-jan-2023
6,IndiGo,Kolkata,Raipur,6h 45m,1 Stop,11:05,17:50,"9,358",07-jan-2023
7,IndiGo,Kolkata,Raipur,8h 50m,1 Stop,09:00,17:50,"9,358",07-jan-2023
8,Vistara,Kolkata,Raipur,26h 30m,1 Stop,07:10,09:40\n+ 1 day,"14,590",07-jan-2023
9,Vistara,Kolkata,Raipur,12h 30m,1 Stop,07:10,19:40,"14,907",07-jan-2023
10,IndiGo,Kolkata,Raipur,10h 50m,1 Stop,09:00,19:50,"14,942",07-jan-2023
11,Vistara,Kolkata,Raipur,13h 15m,1 Stop,20:25,09:40\n+ 1 day,"15,326",07-jan-2023
12,Vistara,Kolkata,Raipur,23h 15m,1 Stop,20:25,19:40\n+ 1 day,"15,326",07-jan-2023
13,IndiGo,Kolkata,Raipur,5h 55m,1 Stop,13:55,19:50,"15,467",07-jan-2023
14,Vistara,Kolkata,Raipur,14h 55m,1 Stop,18:45,09:40\n+ 1 day,"17,006",07-jan-2023
15,Vistara,Kolkata,Raipur,24h 55m,1 Stop,18:45,19:40\n+ 1 day,"17,006",07-jan-2023
16,Vistara,Kolkata,Raipur,23h 25m,1 Stop,10:15,09:40\n+ 1 day,"18,056",07-jan-2023
17,Vistara,Kolkata,Raipur,9h 25m,1 Stop,10:15,19:40,"18,372",07-jan-2023
18,Vistara,Kolkata,Raipur,18h 20m,1 Stop,15:20,09:40\n+ 1 day,"23,831",07-jan-2023
19,Vistara,Kolkata,Raipur,14h 55m,2 Stop(s),18:45,09:40\n+ 1 day,"24,881",07-jan-2023
20,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"24,881",07-jan-2023
21,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"26,141",07-jan-2023
22,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"26,141",07-jan-2023
23,Air India,Kolkata,Raipur,26h 15m,1 Stop,09:30,11:45\n+ 1 day,"29,996",07-jan-2023
24,Air India,Kolkata,Raipur,19h 30m,1 Stop,16:15,11:45\n+ 1 day,"31,886",07-jan-2023
25,Air India,Kolkata,Raipur,18h 35m,2 Stop(s),17:10,11:45\n+ 1 day,"33,760",07-jan-2023
26,Air India,Kolkata,Raipur,18h 30m,1 Stop,17:15,11:45\n+ 1 day,"35,036",07-jan-2023
27,Air India,Kolkata,Raipur,18h 35m,2 Stop(s),17:10,11:45\n+ 1 day,"35,795",07-jan-2023
28,Air India,Kolkata,Raipur,20h 20m,2 Stop(s),15:25,11:45\n+ 1 day,"37,241",07-jan-2023
29,Air India,Kolkata,Raipur,20h 20m,2 Stop(s),15:25,11:45\n+ 1 day,"37,241",07-jan-2023
30,Air India,Kolkata,Raipur,16h 45m,2 Stop(s),19:00,11:45\n+ 1 day,"46,764",07-jan-2023

In [140]:
url='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=RPR&destinationCountry=IN&flexi=0&flight_depart_date=07%2F01%2F2023&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=222830016237&version=1.1&viewName=normal'
driver.get(url)

# NEXT DATA

In [141]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [142]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [143]:
print(len(Flight_Name))
print(len(From))
print(len(To))
print(len(Time_Taken))
print(len(Stopage))
print(len(Price))
print(len(Departure_Time))
print(len(Arrived_Time))

23
23
23
23
23
23
23
23

In [144]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"08-jan-2023"})

In [145]:
Flight_Prediction4.to_csv('Flight_Prediction_36')

In [146]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,07:35,09:10,"6,122",08-jan-2023
1,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,15:15,16:50,"9,901",08-jan-2023
2,IndiGo,Kolkata,Raipur,2h 20m,Non Stop,17:10,19:30,"9,901",08-jan-2023
3,IndiGo,Kolkata,Raipur,7h 00m,1 Stop,06:00,13:00,"10,658",08-jan-2023
4,IndiGo,Kolkata,Raipur,5h 35m,1 Stop,05:25,11:00,"12,315",08-jan-2023
5,IndiGo,Kolkata,Raipur,5h 35m,1 Stop,07:25,13:00,"12,810",08-jan-2023
6,Vistara,Kolkata,Raipur,12h 30m,1 Stop,07:10,19:40,"17,006",08-jan-2023
7,Vistara,Kolkata,Raipur,23h 15m,1 Stop,20:25,19:40\n+ 1 day,"17,006",08-jan-2023
8,Vistara,Kolkata,Raipur,13h 15m,1 Stop,20:25,09:40\n+ 1 day,"17,322",08-jan-2023
9,Vistara,Kolkata,Raipur,26h 30m,1 Stop,07:10,09:40\n+ 1 day,"17,322",08-jan-2023
10,IndiGo,Kolkata,Raipur,11h 45m,1 Stop,23:15,11:00\n+ 1 day,"19,645",08-jan-2023
11,Vistara,Kolkata,Raipur,9h 25m,1 Stop,10:15,19:40,"20,156",08-jan-2023
12,Vistara,Kolkata,Raipur,24h 55m,1 Stop,18:45,19:40\n+ 1 day,"20,156",08-jan-2023
13,IndiGo,Kolkata,Raipur,11h 00m,1 Stop,08:50,19:50,"20,380",08-jan-2023
14,Vistara,Kolkata,Raipur,14h 55m,1 Stop,18:45,09:40\n+ 1 day,"20,472",08-jan-2023
15,Vistara,Kolkata,Raipur,23h 25m,1 Stop,10:15,09:40\n+ 1 day,"20,472",08-jan-2023
16,IndiGo,Kolkata,Raipur,5h 55m,1 Stop,13:55,19:50,"22,480",08-jan-2023
17,IndiGo,Kolkata,Raipur,9h 00m,1 Stop,08:50,17:50,"23,550",08-jan-2023
18,Vistara,Kolkata,Raipur,18h 20m,1 Stop,15:20,09:40\n+ 1 day,"24,147",08-jan-2023
19,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"26,981",08-jan-2023
20,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"27,296",08-jan-2023
21,Vistara,Kolkata,Raipur,14h 55m,2 Stop(s),18:45,09:40\n+ 1 day,"29,607",08-jan-2023
22,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"29,816",08-jan-2023

# NEXT DATA

In [147]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [148]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [149]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"09-jan-2023"})

In [150]:
Flight_Prediction4.to_csv('Flight_Prediction_37')

In [151]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Kolkata,Raipur,2h 20m,Non Stop,17:10,19:30,"5,462",09-jan-2023
1,IndiGo,Kolkata,Raipur,9h 00m,1 Stop,08:50,17:50,"6,932",09-jan-2023
2,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,15:15,16:50,"7,300",09-jan-2023
3,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,07:35,09:10,"7,750",09-jan-2023
4,IndiGo,Kolkata,Raipur,5h 35m,1 Stop,05:25,11:00,"8,286",09-jan-2023
5,IndiGo,Kolkata,Raipur,7h 00m,1 Stop,06:00,13:00,"8,286",09-jan-2023
6,IndiGo,Kolkata,Raipur,5h 55m,1 Stop,13:55,19:50,"13,439",09-jan-2023
7,IndiGo,Kolkata,Raipur,11h 00m,1 Stop,08:50,19:50,"13,439",09-jan-2023
8,IndiGo,Kolkata,Raipur,5h 35m,1 Stop,07:25,13:00,"14,540",09-jan-2023
9,Vistara,Kolkata,Raipur,13h 15m,1 Stop,20:25,09:40\n+ 1 day,"14,590",09-jan-2023
10,Vistara,Kolkata,Raipur,14h 55m,1 Stop,18:45,09:40\n+ 1 day,"14,590",09-jan-2023
11,Vistara,Kolkata,Raipur,23h 15m,1 Stop,20:25,19:40\n+ 1 day,"14,906",09-jan-2023
12,Vistara,Kolkata,Raipur,24h 55m,1 Stop,18:45,19:40\n+ 1 day,"14,907",09-jan-2023
13,Vistara,Kolkata,Raipur,12h 30m,1 Stop,07:10,19:40,"16,061",09-jan-2023
14,Vistara,Kolkata,Raipur,26h 30m,1 Stop,07:10,09:40\n+ 1 day,"16,061",09-jan-2023
15,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"26,142",09-jan-2023
16,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"27,402",09-jan-2023
17,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"27,402",09-jan-2023
18,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"30,552",09-jan-2023

# NEXT DATA

In [152]:
# Scraping details of product for which you want
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [153]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [154]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"10-jan-2023"})

In [155]:
Flight_Prediction4.to_csv('Flight_Prediction_37')

In [156]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Kolkata,Raipur,8h 20m,1 Stop,05:25,13:45,"4,454",10-jan-2023
1,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,07:35,09:10,"5,166",10-jan-2023
2,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,15:15,16:50,"5,166",10-jan-2023
3,IndiGo,Kolkata,Raipur,2h 20m,Non Stop,17:10,19:30,"5,166",10-jan-2023
4,IndiGo,Kolkata,Raipur,5h 55m,1 Stop,13:55,19:50,"11,421",10-jan-2023
5,IndiGo,Kolkata,Raipur,11h 00m,1 Stop,08:50,19:50,"11,421",10-jan-2023
6,IndiGo,Kolkata,Raipur,9h 00m,1 Stop,08:50,17:50,"11,722",10-jan-2023
7,Vistara,Kolkata,Raipur,13h 15m,1 Stop,20:25,09:40\n+ 1 day,"14,590",10-jan-2023
8,Vistara,Kolkata,Raipur,14h 55m,1 Stop,18:45,09:40\n+ 1 day,"14,590",10-jan-2023
9,Vistara,Kolkata,Raipur,18h 20m,1 Stop,15:20,09:40\n+ 1 day,"14,590",10-jan-2023
10,Vistara,Kolkata,Raipur,23h 15m,1 Stop,20:25,19:40\n+ 1 day,"14,590",10-jan-2023
11,Vistara,Kolkata,Raipur,23h 25m,1 Stop,10:15,09:40\n+ 1 day,"14,590",10-jan-2023
12,Vistara,Kolkata,Raipur,26h 30m,1 Stop,07:10,09:40\n+ 1 day,"14,590",10-jan-2023
13,Vistara,Kolkata,Raipur,24h 55m,1 Stop,18:45,19:40\n+ 1 day,"14,591",10-jan-2023
14,Vistara,Kolkata,Raipur,12h 30m,1 Stop,07:10,19:40,"14,906",10-jan-2023
15,Vistara,Kolkata,Raipur,9h 25m,1 Stop,10:15,19:40,"14,907",10-jan-2023
16,Air India,Kolkata,Raipur,19h 30m,1 Stop,16:15,11:45\n+ 1 day,"15,747",10-jan-2023
17,Air India,Kolkata,Raipur,26h 15m,1 Stop,09:30,11:45\n+ 1 day,"15,747",10-jan-2023
18,Air India,Kolkata,Raipur,18h 30m,1 Stop,17:15,11:45\n+ 1 day,"16,587",10-jan-2023
19,Air India,Kolkata,Raipur,18h 35m,2 Stop(s),17:10,11:45\n+ 1 day,"19,632",10-jan-2023
20,Air India,Kolkata,Raipur,18h 35m,2 Stop(s),17:10,11:45\n+ 1 day,"19,632",10-jan-2023
21,Air India,Kolkata,Raipur,20h 20m,2 Stop(s),15:25,11:45\n+ 1 day,"21,522",10-jan-2023
22,Air India,Kolkata,Raipur,20h 20m,2 Stop(s),15:25,11:45\n+ 1 day,"21,522",10-jan-2023
23,Vistara,Kolkata,Raipur,16h 10m,2 Stop(s),17:30,09:40\n+ 1 day,"22,674",10-jan-2023
24,Vistara,Kolkata,Raipur,16h 10m,2 Stop(s),17:30,09:40\n+ 1 day,"22,674",10-jan-2023
25,Vistara,Kolkata,Raipur,9h 20m,2 Stop(s),10:20,19:40,"24,672",10-jan-2023
26,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"26,141",10-jan-2023
27,Air India,Kolkata,Raipur,16h 45m,2 Stop(s),19:00,11:45\n+ 1 day,"31,917",10-jan-2023

# NEXT DATA

In [157]:
Flight_Name=[]
From=[]
To=[]
Time_Taken=[]
Stopage=[]
Price=[]
Departure_Time=[]
Arrived_Time=[]

In [158]:
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//span[@class='i-b text ellipsis']")
    for i in name:
        Flight_Name.append(i.text)
except NoSuchElementException:
    Flight_Name.append('Nan')
    
# scraping  From Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        From.append(i.text)
except NoSuchElementException:
    From.append('-')

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[2][@class='fs-10 font-lightgrey no-wrap city ellipsis']")
    for i in name:
        To.append(i.text)
except NoSuchElementException:
    To.append('-')


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[1][@class='fs-12 bold du mb-2']")
    for i in name:
        Time_Taken.append(i.text)
except NoSuchElementException:
    Time_Taken.append('-')
    
# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']//span[1]")
    for i in name:
        Stopage.append(i.text)
except NoSuchElementException:
    Stopage.append('-')
    

try:
    op_ser = driver.find_elements(By.XPATH,'//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for os in op_ser:
        Price.append(os.text)
except NoSuchElementException:
    Price.append('-')
    
    

# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//div[@class='i-b pr']")
    for i in name:
        Departure_Time.append(i.text)
except NoSuchElementException:
    Departure_Time.append('-')
    


# scraping  Flight Name
try:
    name = driver.find_elements(By.XPATH,"//p[@class='bold fs-15 mb-2 pr time']")
    for i in name:
        Arrived_Time.append(i.text)
except NoSuchElementException:
    Arrived_Time.append('-')

In [159]:
#Lets make dataframe
import pandas as pd
Flight_Prediction4=pd.DataFrame({"Flight Name":Flight_Name,"From":From,"To":To,"Time Taken":Time_Taken,"Stopage":Stopage,"Departure Time":Departure_Time,"Arrived Time":Arrived_Time,"Price":Price,"Date Of Journey":"11-jan-2023"})

In [160]:
Flight_Prediction4.to_csv('Flight_Prediction_38')

In [161]:
Flight_Prediction4

,Flight Name,From,To,Time Taken,Stopage,Departure Time,Arrived Time,Price,Date Of Journey
0,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,07:35,09:10,"5,166",11-jan-2023
1,IndiGo,Kolkata,Raipur,1h 35m,Non Stop,15:15,16:50,"5,166",11-jan-2023
2,IndiGo,Kolkata,Raipur,2h 20m,Non Stop,17:10,19:30,"5,166",11-jan-2023
3,IndiGo,Kolkata,Raipur,8h 20m,1 Stop,05:25,13:45,"6,174",11-jan-2023
4,IndiGo,Kolkata,Raipur,5h 35m,1 Stop,07:25,13:00,"8,286",11-jan-2023
5,IndiGo,Kolkata,Raipur,7h 00m,1 Stop,06:00,13:00,"8,286",11-jan-2023
6,IndiGo,Kolkata,Raipur,11h 00m,1 Stop,08:50,19:50,"10,237",11-jan-2023
7,IndiGo,Kolkata,Raipur,5h 55m,1 Stop,13:55,19:50,"10,289",11-jan-2023
8,IndiGo,Kolkata,Raipur,9h 00m,1 Stop,08:50,17:50,"10,890",11-jan-2023
9,Vistara,Kolkata,Raipur,13h 15m,1 Stop,20:25,09:40\n+ 1 day,"14,590",11-jan-2023
10,Vistara,Kolkata,Raipur,14h 55m,1 Stop,18:45,09:40\n+ 1 day,"14,590",11-jan-2023
11,Vistara,Kolkata,Raipur,18h 20m,1 Stop,15:20,09:40\n+ 1 day,"14,590",11-jan-2023
12,Vistara,Kolkata,Raipur,23h 15m,1 Stop,20:25,19:40\n+ 1 day,"14,590",11-jan-2023
13,Vistara,Kolkata,Raipur,23h 25m,1 Stop,10:15,09:40\n+ 1 day,"14,590",11-jan-2023
14,Vistara,Kolkata,Raipur,26h 30m,1 Stop,07:10,09:40\n+ 1 day,"14,590",11-jan-2023
15,Vistara,Kolkata,Raipur,9h 25m,1 Stop,10:15,19:40,"14,591",11-jan-2023
16,Vistara,Kolkata,Raipur,12h 30m,1 Stop,07:10,19:40,"14,591",11-jan-2023
17,Vistara,Kolkata,Raipur,24h 55m,1 Stop,18:45,19:40\n+ 1 day,"14,591",11-jan-2023
18,Air India,Kolkata,Raipur,18h 30m,1 Stop,17:15,11:45\n+ 1 day,"15,747",11-jan-2023
19,Air India,Kolkata,Raipur,19h 30m,1 Stop,16:15,11:45\n+ 1 day,"15,747",11-jan-2023
20,Air India,Kolkata,Raipur,26h 15m,1 Stop,09:30,11:45\n+ 1 day,"15,747",11-jan-2023
21,Air India,Kolkata,Raipur,18h 35m,2 Stop(s),17:10,11:45\n+ 1 day,"19,632",11-jan-2023
22,Air India,Kolkata,Raipur,20h 20m,2 Stop(s),15:25,11:45\n+ 1 day,"21,522",11-jan-2023
23,Air India,Kolkata,Raipur,20h 20m,2 Stop(s),15:25,11:45\n+ 1 day,"21,522",11-jan-2023
24,Air India,Kolkata,Raipur,18h 35m,2 Stop(s),17:10,11:45\n+ 1 day,"22,278",11-jan-2023
25,Vistara,Kolkata,Raipur,16h 10m,2 Stop(s),17:30,09:40\n+ 1 day,"22,674",11-jan-2023
26,Vistara,Kolkata,Raipur,16h 10m,2 Stop(s),17:30,09:40\n+ 1 day,"22,989",11-jan-2023
27,Air India,Kolkata,Raipur,16h 45m,2 Stop(s),19:00,11:45\n+ 1 day,"23,307",11-jan-2023
28,Vistara,Kolkata,Raipur,23h 00m,2 Stop(s),20:40,19:40\n+ 1 day,"27,716",11-jan-2023
29,Vistara,Kolkata,Raipur,9h 20m,2 Stop(s),10:20,19:40,"28,241",11-jan-2023

In [ ]:
# Ne